apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: url-shortener-metrics
  namespace: url-shortener
  labels:
    app: url-shortener
spec:
  selector:
    matchLabels:
      app: url-shortener
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-metrics
  namespace: url-shortener
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
  endpoints:
  - port: redis
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s