# Cloud Build configuration with parameterized variables
# This version uses substitution variables that can be set in triggers or via CLI

steps:
# Generate terraform.tfvars from environment variables
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    # Set up environment variables from Cloud Build substitutions
    export ORGANIZATION_ID="${_ORGANIZATION_ID}"
    export BILLING_ACCOUNT="${_BILLING_ACCOUNT}"
    export FOLDER_ID="${_FOLDER_ID}"
    export PROJECT_PREFIX="${_PROJECT_PREFIX}"
    export DOMAIN_NAME="${_DOMAIN_NAME}"

    # Generate terraform.tfvars
    ./scripts/generate-tfvars.sh ${_ENVIRONMENT}

# Terraform plan
- name: 'hashicorp/terraform:1.6'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    cd infra/environments/${_ENVIRONMENT}
    terraform init
    terraform plan -var-file=terraform.tfvars

# Terraform apply (if _AUTO_APPLY is true)
- name: 'hashicorp/terraform:1.6'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    cd infra/environments/${_ENVIRONMENT}
    if [ "${_AUTO_APPLY}" = "true" ]; then
      terraform apply -var-file=terraform.tfvars -auto-approve
    else
      echo "Skipping apply - _AUTO_APPLY is not true"
    fi

# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - '${_REGISTRY_URL}/${_PROJECT_PREFIX}-${_ENVIRONMENT}-app/url-shortener:$COMMIT_SHA'
  - '-t'
  - '${_REGISTRY_URL}/${_PROJECT_PREFIX}-${_ENVIRONMENT}-app/url-shortener:latest'
  - '.'

# Push the container image
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'push'
  - '${_REGISTRY_URL}/${_PROJECT_PREFIX}-${_ENVIRONMENT}-app/url-shortener:$COMMIT_SHA'

- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'push'
  - '${_REGISTRY_URL}/${_PROJECT_PREFIX}-${_ENVIRONMENT}-app/url-shortener:latest'

# Deploy to GKE
- name: 'gcr.io/cloud-builders/gke-deploy'
  args:
  - 'run'
  - '--filename=k8s/'
  - '--image=${_REGISTRY_URL}/${_PROJECT_PREFIX}-${_ENVIRONMENT}-app/url-shortener:$COMMIT_SHA'
  - '--cluster=${_PROJECT_PREFIX}-${_ENVIRONMENT}-url-shortener'
  - '--location=${_REGION}'
  - '--namespace=url-shortener'

# Default substitution variables
substitutions:
  _ENVIRONMENT: 'dev'                              # dev or prod
  _ORGANIZATION_ID: '123456789012'                 # Your GCP organization ID
  _BILLING_ACCOUNT: '012345-678901-234567'         # Your billing account
  _FOLDER_ID: ''                                   # Optional folder ID
  _PROJECT_PREFIX: 'urlshort'                      # Project prefix
  _DOMAIN_NAME: 'dev.short.example.com'           # Domain name
  _REGION: 'europe-west1'                         # GCP region
  _REGISTRY_URL: 'gcr.io'                         # Container registry
  _AUTO_APPLY: 'false'                            # Set to 'true' for auto-apply

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '1800s'