name: Destroy All

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

env:
  TF_VAR_organization_id: ${{ secrets.GCP_ORG_ID }}
  TF_VAR_billing_account: ${{ secrets.GCP_BILLING_ACCOUNT }}
  TF_VAR_domain_name: ${{ secrets.DOMAIN_NAME }}
  TF_VAR_folder_id: ${{ secrets.GCP_FOLDER_ID }}
  TF_VAR_project_prefix: ${{ secrets.PROJECT_PREFIX }}
  TF_VAR_notification_email: ${{ secrets.NOTIFICATION_EMAIL }}
  TF_VAR_iap_users: ${{ secrets.IAP_USERS }}
  REGION: europe-west1
  TERRAFORM_PROJECT_ID: ${{ secrets.GCP_TERRAFORM_PROJECT_ID }}
  TERRAFORM_BUCKET_PREFIX: ${{ secrets.TERRAFORM_BUCKET_PREFIX }}

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Setup Google Cloud Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_TERRAFORM_PROJECT_ID }}

      - name: Terraform Init
        run: make init

      - name: Destroy Dev
        run: make destroy-dev

      - name: Destroy Shared Infra
        run: make destroy-shared
