name: Dev Infra

on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'
      - '.github/workflows/dev-infra.yml'
      - '.github/workflows/shared-infra.yml'
      - 'Makefile'
  workflow_dispatch:

jobs:
  shared-infra:
    uses: ./.github/workflows/infra.yml
    with:
      environment: shared
    secrets: inherit

  dev-infra:
    needs: shared-infra
    uses: ./.github/workflows/infra.yml
    with:
      environment: dev
    secrets: inherit
