name: Shared Infra

on:
  push:
    branches:
      - main
    paths-ignore:
        - '.github/workflows/destroy-all.yml'
        - 'docs/**'
        - 'k8s/**'
  workflow_dispatch:

jobs:
  infra:
    uses: ./.github/workflows/infra.yml
    with:
      environment: shared
    secrets: inherit
